source "https://rubygems.org"

gemspec

gem "google-cloud-core", path: "../google-cloud-core"
gem "google-cloud-env", path: "../google-cloud-env"

gem "rake", "~> 12.3"

gem "faraday-detailed_logger", "~> 2.2"
